### ISSUE TITLE
Could criteria not be a list of tiggers?

### ISSUE THREAD

**Issue by Rooba** [StackStorm/st2docs#1169]
In the docs -- 

> Due to a issue[^1][^2] in PyYAML, criteria keys must be unique. This sometimes becomes relevant when you want to apply different operators (like contains and ncontains) to the same trigger data:
>
> ```yaml
> criteria:
>   trigger.payload.commit.tags:  # duplicate key - ignored!
>     type: ncontains
>     pattern: StackStorm
>   trigger.payload.commit.tags:  # duplicate key - evaluated
>     type: contains
>     pattern: pull request
>   trigger.payload.commit.message:  # unique key - evaluated
>     type: ncontains
>     pattern: ST2
> ```

[^1]:https://github.com/yaml/pyyaml/issues/41
[^2]:https://github.com/yaml/pyyaml/issues/165

---

I would think the following would be a fairly simple way to get around that issue

```yaml
criteria:
  - trigger.payload.commit.tags:
      type: ncontains
      pattern: StackStorm
  - trigger.payload.commit.tags:
      type: contains
      pattern: pull request
  - trigger.payload.commit.message:
      type: ncontains
      pattern: ST2
```

or even something like 

```yaml
criteria:
  - trigger: payload.commit.tags
    type: ncontains
    pattern: StackStorm
  - trigger: payload.commit.tags 
    type: contains
    pattern: pull request
  - trigger: payload.commit.message
    type: ncontains
    pattern: ST2
```
