### ISSUE TITLE
Clarify how to get vars from nested chains

### ISSUE THREAD

**Issue by Mierdin** [StackStorm/st2docs#556]
https://docs.stackstorm.com/actionchain.html#passing-data-between-different-workflows only briefly mentions how actionchains publish variables:

> The cumulative published variables are also available in the result of an ActionChain execution under the published property

Could elaborate on this with an example:

```
---
    chain:

        -
            name: "task1"
            ref: "testpack.chain-nested"
            on-success: "task2"
        -
            name: "task2"
            ref: "core.local"
            parameters:
              cmd: "echo 'inner task said {{ task1.published.myvar }}'"

```

```
---
    chain:

          - name: "innertask1"
            ref: "core.noop"
            publish:
                myvar: "FOO"
```
